include: package:flutter_lints/flutter.yaml

# 활성화할 실험 기능 (옵셔널)
enable-experiment:
  - non-nullable

linter:
  rules:
    # Flutter 스타일 기본
    avoid_print: true
    prefer_const_constructors: true
    prefer_final_fields: true
    prefer_single_quotes: true

    # Clean Architecture / 팀 규칙
    unused_import: true
    avoid_relative_lib_imports: true
    file_names: snake_case
    always_specify_types: true

analyzer:
  exclude:
    - "**/*.g.dart" # 코드 생성 파일 제외
    - "**/*.freezed.dart"
    - "**/build/**"
